### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by QinYouming** [iq-motion-control/iq-module-communication-arduino#10]
**Describe the bug 1**
I followed the description of flashing new firmware, but it keeps prompting this and prevents me from proceeding:
![image](https://user-images.githubusercontent.com/11729305/90332957-f1808480-dff3-11ea-822b-abc1aefb94b6.png)
**Additional context**
I did everything in Administrator mode, and before clicking on "Next" on the "STMFlashLoader Demo", I did hear the jingle. There should be nothing wrong with my connection since it successfully connected to the IQ Control Center, and I tried the PWM test a couple of times, and the motor does spin.

**Describe the bug 2**
The Arduino example code has no issue compiling and uploading, but the motor is not responding whatsoever. While running the example code, I used an oscilloscope to monitor what was happening, and I see signals on both TX and RX for a couple of seconds:
![image](https://user-images.githubusercontent.com/11729305/90333247-cb101880-dff6-11ea-90e9-b73da966d320.png)
and after a few seconds, only TX signal is left:
![image](https://user-images.githubusercontent.com/11729305/90333248-d3685380-dff6-11ea-87ff-6dce037f2709.png)
**Additional context**
I was using the same hardware setup as the setting I successfully connected to the IQ Control Center. I'm using Arduino Uno for UART, and Analog discovery 2 for data acquisition. I cannot flash new firmware in, so the firmware I'm using now is straight out of the box.

**Describe the bug 3**
the link: www.iq-control.com/documentation fails
And I can't find information regards the differences among the 3 firmwares.

**Comment by iq-matt** [comment]
Hi!  Sorry this is very late.  I hope you solved your issues.  Regardless, here are some steps.

First, a new version of the GUI is released.  You won't need to use ST's Flash Loader Demonstrator anymore.  
Second, if you want to continue using the Flash Loader Demonstrator, you must click next BEFORE the jingle occurs again.  If you wait until the jingle happens it to too late.

On another note, we've had many customers have issues using Arduinos as USB to UART passthroughs.  We highly recommend using a dedicated FTDI or CP2102 or similar USB to UART chip for reflashing.

Finally, thank you for letting us know about the broken links.  We updated our website/host and sadly all of the links broke there.  We are working on fixing them, as well as update the documentation to use Read the Docs.

**Comment by IQ-Malik** [comment]
Here's the link for our Read the Docs Communications Manual: https://iqmotion.readthedocs.io/en/latest/

Closing this issue, but please reopen if you're still having trouble after this
