### ISSUE TITLE
Broken URLs everywhere

### ISSUE THREAD

**Issue by gitcnd** [iq-motion-control/iq-module-communication-arduino#12]
**Describe the bug**
All your documentation is broken - links to download software ( https://www.iq-control.com/control-center ), to get the firmware, to install the libraries, everything in google, and so on and on .... all 404s

Your idea to update the url in this one place was totally the wrong solution - you need to update the web server on iq-control to either display all the documentation, or to redirect to the new place.  You can't change PDF files on our hard drives, or the contents of google searches, etc etc - but you CAN fix that web server.

**Comment by IQ-Malik** [comment]
Please refer to our Read The Docs Communications Manual: https://iqmotion.readthedocs.io/en/latest/
